# [dbo].[Estudiantes]

In [0]:
USE [Dispro]
GO

In [0]:
/****** Object:  Table [dbo].[Estudiantes]    Script Date: 15/04/2025 6:21:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiantes](
	[IdEstudiante] [int] IDENTITY(1,1) NOT NULL,
	[TipoDocumento] [nvarchar](50) NOT NULL,
	[NumeroDocumento] [nvarchar](50) NOT NULL,
	[NombresEstudiante] [nvarchar](100) NOT NULL,
	[ApellidosEstudiante] [nvarchar](100) NOT NULL,
	[Grado] [nvarchar](50) NOT NULL,
	[Seccion] [nvarchar](50) NOT NULL,
	[Jornada] [nvarchar](50) NOT NULL,
	[IdAcudiente] [nvarchar](20) NOT NULL,
	[NombreAcudiente] [nvarchar](100) NOT NULL,
	[ApellidoAcudiente] [nvarchar](100) NOT NULL,
	[TelefonoAcudiente] [nvarchar](15) NOT NULL,
	[CorreoAcudiente] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEstudiante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[proceso_1]

In [0]:
/****** Object:  Table [dbo].[proceso_1]    Script Date: 15/04/2025 6:21:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[proceso_1](
	[identificacion] [int] NULL,
	[nombres] [varchar](100) NULL,
	[apellidos] [varchar](100) NULL,
	[grado] [varchar](50) NULL,
	[seccion] [varchar](50) NULL,
	[jornada] [varchar](50) NULL,
	[idacudiente] [int] NULL,
	[nombre_acudiente] [varchar](100) NULL,
	[apellidos_acudiente] [varchar](100) NULL,
	[correoacudiente] [varchar](100) NULL,
	[telefono] [int] NULL,
	[rutafoto] [varchar](255) NULL,
	[rutavideos] [varchar](255) NULL,
	[estado] [varchar](50) NULL,
	[falta_cometida] [varchar](255) NULL,
	[descargos] [varchar](255) NULL,
	[compromiso] [varchar](255) NULL
) ON [PRIMARY]
GO

# [dbo].[proceso_2]

In [0]:
/****** Object:  Table [dbo].[proceso_2]    Script Date: 15/04/2025 6:21:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[proceso_2](
	[id] [int] NULL,
	[identificacion] [nvarchar](250) NULL,
	[nombres] [nvarchar](250) NULL,
	[apellidos] [nvarchar](250) NULL,
	[grado] [nvarchar](250) NULL,
	[seccion] [nvarchar](250) NULL,
	[jornada] [nvarchar](250) NULL,
	[idacudiente] [nvarchar](250) NULL,
	[nombre_acudiente] [nvarchar](250) NULL,
	[apellidos_acudiente] [nvarchar](250) NULL,
	[correoacudiente] [nvarchar](250) NULL,
	[telefono] [nvarchar](250) NULL,
	[estado] [nvarchar](250) NULL,
	[falta_cometida] [nvarchar](250) NULL,
	[rutafoto] [text] NULL,
	[mediador1] [nvarchar](250) NULL,
	[mediador2] [nvarchar](250) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Usuarios]

In [0]:
/****** Object:  Table [dbo].[Usuarios]    Script Date: 15/04/2025 6:21:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NombresCompletos] [nvarchar](100) NULL,
	[ApellidosUsuario] [nvarchar](100) NULL,
	[CorreoElectronico] [nvarchar](100) NULL,
	[Contrasena] [nvarchar](100) NULL,
	[NumeroTelefono] [nvarchar](15) NULL,
	[usuario] [nvarchar](255) NULL,
	[Rol] [nvarchar](50) NULL,
	[RutaFirma] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [DF__proceso_2__estad__1BC821DD]

In [0]:
ALTER TABLE [dbo].[proceso_2] ADD  DEFAULT ('Activo') FOR [estado]
GO